-keep,allowoptimization,allowobfuscation class com.jaredrummler.android.colorpicker.**
-keep,allowoptimization,allowobfuscation class androidx.annotation.**
-dontwarn sun.security.internal.spec.**
-dontwarn sun.security.provider.**
-dontwarn com.jaredrummler.android.colorpicker.**
-dontwarn androidx.annotation.**