name: Make Release

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Source Code Download
        run: git clone --branch stable --single-branch --recurse-submodules https://github.com/siavash79/PixelXpert.git .

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Shell Scripts Permissions
        run: chmod +x .github/*.sh

      - name: Version Bump
        run: .github/bumpVersion.sh

      - name: Gradlew Permissions
        run: chmod +x gradlew

      - name: Signature files preparation
        run: |
          if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
            echo storePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> ReleaseKey.properties
            echo keyAlias='${{ secrets.ALIAS }}' >> ReleaseKey.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> ReleaseKey.properties
            echo storeFile='${{ github.workspace }}/ReleaseKey.jks' >> ReleaseKey.properties
            echo ${{ secrets.SIGNING_KEY }} | base64 --decode > ${{ github.workspace }}/ReleaseKey.jks
          fi

      - name: Gradle Build
        run: ./gradlew assembleRelease

      - name: Magisk Module Generation
        run: .github/make_zip.sh

      - name: Upload Zip
        uses: actions/upload-artifact@v3
        with:
          name: PixelXpert.zip
          path: output

      - name: Release the binaries
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref_name }}
          prerelease: false
          draft: false
          artifacts: 'output/*.*'
          bodyFile: 'releaseNotes.md'

      - name: Commit version bump
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'stable'
          commit-message: 'Version update: Release'
          force-add: 'true'
          files: MagiskModBase/module.prop MagiskModAddon/module.prop app/build.gradle MagiskModuleUpdate.json MagiskModuleUpdate_Full.json MagiskModuleUpdate_Xposed.json latestStable.json MagiskChangelog.md
          name: GitHub
          email: pixelxpert@siava.sh

      - name: Telegram Channel Post
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.AOSPMODS_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ env.TMessage }}
          format: markdown
